//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSeguros.Models.DBP
{
    using System;
    using System.Collections.Generic;
    
    public partial class afiliados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public afiliados()
        {
            this.desactivaciones = new HashSet<desactivaciones>();
        }
    
        public int id { get; set; }
        public string cedula { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string lugar_residencia { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public System.DateTime fecha { get; set; }
        public int valor_plan { get; set; }
        public int monto_asegurado { get; set; }
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<desactivaciones> desactivaciones { get; set; }
    }
}
